### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by mpalmerlee** [3rd-Eden/jackpot#10]
We just started seeing this error in our development servers related to using the node-memcached package.  since it specifies jackpot version >= 0.0.2 with the recent 0.0.5 release we started seeing this error.

 at EventEmitter.memcached.delegateCallback (...node_modules/memcached/lib/memcached.js:622:12)
    at EventEmitter.rawDataReceived (...node_modules/memcached/lib/memcached.js:681:22)
    at EventEmitter.BufferBuffer (...node_modules/memcached/lib/memcached.js:613:12)
    at Socket.bowlofcurry (...node_modules/memcached/lib/utils.js:108:15)

We can shrink wrap our way out of this issue, but wanted to let you know.

thanks,
-Matt

**Comment by mpalmerlee** [comment]
My coworker just submitted a pull request for this issue:
https://github.com/3rd-Eden/jackpot/pull/11

**Comment by 3rd-Eden** [comment]
@mpalmerlee Thanks for the heads up! The patch of #11 is merged and released `0.0.6` could you confirm that this resolves the issues for you?

**Comment by mpalmerlee** [comment]
Yeah, it looks good with version 0.0.6

thanks!

Might want to add some tests against memcached with an async call, that's what exposed this issue.

**Comment by 3rd-Eden** [comment]
@mpalmerlee I think a test should be added in Jackpot against this to prevent double function calls.
